# Generated by Django 3.0.8 on 2020-07-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20200718_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='contact',
        ),
    ]
